#!/bin/sh
# Helper script for the SecureShellState class to pass a password value to
# `ssh` as part of the OpenSSH SSH_ASKPASS protocol.
# <https://linux.die.net/man/1/ssh>
set -o errexit
echo "${SSH_PASSWORD}"
unset SSH_PASSWORD
exit 0
